// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1W5DMpeAZJTu0APzsn3x6uKfnhaGyrg',
    appId: '1:806653602396:web:3c548e071b5ae93678d499',
    messagingSenderId: '806653602396',
    projectId: 'projetnitroservice',
    authDomain: 'projetnitroservice.firebaseapp.com',
    storageBucket: 'projetnitroservice.firebasestorage.app',
    measurementId: 'G-4YJELH06D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEB96vUH6Ba-57fWjP7ssQfk_Q4eSU0YY',
    appId: '1:806653602396:android:9cd2d4b4ef3ee04a78d499',
    messagingSenderId: '806653602396',
    projectId: 'projetnitroservice',
    storageBucket: 'projetnitroservice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYiMZ4wqG8bu7Ep_98ImvmjJIC2LL2kIU',
    appId: '1:806653602396:ios:d0b8e3efa7b5fb0978d499',
    messagingSenderId: '806653602396',
    projectId: 'projetnitroservice',
    storageBucket: 'projetnitroservice.firebasestorage.app',
    iosBundleId: 'com.example.nitroservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYiMZ4wqG8bu7Ep_98ImvmjJIC2LL2kIU',
    appId: '1:806653602396:ios:d0b8e3efa7b5fb0978d499',
    messagingSenderId: '806653602396',
    projectId: 'projetnitroservice',
    storageBucket: 'projetnitroservice.firebasestorage.app',
    iosBundleId: 'com.example.nitroservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV1W5DMpeAZJTu0APzsn3x6uKfnhaGyrg',
    appId: '1:806653602396:web:711cc93317886e1978d499',
    messagingSenderId: '806653602396',
    projectId: 'projetnitroservice',
    authDomain: 'projetnitroservice.firebaseapp.com',
    storageBucket: 'projetnitroservice.firebasestorage.app',
    measurementId: 'G-YGZY1KKLFP',
  );

}